// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYFPF36TsZz2yzY6di29c4cpF97JD0TqQ',
    appId: '1:471271644685:web:4566e4e5aa6e0165587f44',
    messagingSenderId: '471271644685',
    projectId: 'online-class-bd57e',
    authDomain: 'online-class-bd57e.firebaseapp.com',
    storageBucket: 'online-class-bd57e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY1TNSjrRgjQoGJu9R1uqrcbaDWdqlI0w',
    appId: '1:471271644685:android:aef07ef0e2ae6080587f44',
    messagingSenderId: '471271644685',
    projectId: 'online-class-bd57e',
    storageBucket: 'online-class-bd57e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd-6Fplm0KxrK7s_YVRnzWnwlDfGl7Wek',
    appId: '1:471271644685:ios:3fe9e4794f7c530c587f44',
    messagingSenderId: '471271644685',
    projectId: 'online-class-bd57e',
    storageBucket: 'online-class-bd57e.appspot.com',
    iosBundleId: 'com.example.onlineDars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd-6Fplm0KxrK7s_YVRnzWnwlDfGl7Wek',
    appId: '1:471271644685:ios:3fe9e4794f7c530c587f44',
    messagingSenderId: '471271644685',
    projectId: 'online-class-bd57e',
    storageBucket: 'online-class-bd57e.appspot.com',
    iosBundleId: 'com.example.onlineDars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYFPF36TsZz2yzY6di29c4cpF97JD0TqQ',
    appId: '1:471271644685:web:e145e59550348899587f44',
    messagingSenderId: '471271644685',
    projectId: 'online-class-bd57e',
    authDomain: 'online-class-bd57e.firebaseapp.com',
    storageBucket: 'online-class-bd57e.appspot.com',
  );

}